name: update awesome-stars
on:
  workflow_dispatch:
  schedule:
  - cron: 5 8 * * 0
jobs:
  awesome-stars:
    name: update awesome-stars
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install starred
    - name: update repo
      env:
        GITHUB_TOKEN: ${{ secrets.AWESOME_STARS }}
      run: starred --username krmbzds --repository stars --sort --token ${GITHUB_TOKEN} --message 'Update stars'

